services:
  brands-manago:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT:-3000}
        APP_HOST: ${APP_HOST}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./app:/app
      - ./frontend:/frontend

      # Named volume for node_modules to prevent host conflicts
      - node_modules:/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://${APP_HOST}:${PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - brands-manago-network
    develop:
      watch:
        - action: rebuild
          path: ./app/package.json

volumes:
  node_modules:
    driver: local

networks:
  brands-manago-network:
    driver: bridge
