services:
  brands-manago:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT:-3000}
        APP_HOST: ${APP_HOST}
        BIND_HOST: ${BIND_HOST}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./app:/app
      - ./frontend:/frontend

      # Named volume for node_modules to prevent host conflicts
      - node_modules:/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://${APP_HOST}:${PORT:-3000}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - brands-manago-network
    depends_on:
      - mongodb
    develop:
      watch:
        - action: rebuild
          path: ./app/package.json

  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-brands-manago}
    volumes:
      - mongodb_data:/data/db
      - ./app/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - brands-manago-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules:
    driver: local
  mongodb_data:
    driver: local

networks:
  brands-manago-network:
    driver: bridge
